from bot.db.achievements import award_season_champion, get_user_achievements
from bot.db.analytics import (
    GameDifficultyMetrics,
    GameDifficultyRow,
    GameSpeedBonusStats,
    KpiToday,
    ScoreBucket,
    ScoreTimePoint,
    SpeedBonusLeader,
    UserGameRow,
    UserScorePoint,
    get_avg_score_over_time,
    get_game_difficulty_comparison,
    get_game_difficulty_metrics,
    get_game_raw_data_breakdown,
    get_game_speed_bonus_stats,
    get_kpi_today,
    get_score_distribution,
    get_speed_bonus_leaders,
    get_user_per_game_stats,
    get_user_score_history,
    get_user_submission_dates,
    get_users_for_h2h,
)
from bot.db.config import get_config, set_config
from bot.db.feedback import add_feedback, get_all_feedback
from bot.db.head_to_head import HeadToHeadResult, get_head_to_head
from bot.db.homunculus import add_homunculus_upgrade, get_homunculus_upgrades, homunculus_upgrade_exists
from bot.db.leaderboard import LeaderboardRow, get_leaderboard
from bot.db.logs import get_logs
from bot.db.models import (
    AdminConfig,
    AppLog,
    Base,
    DailyPoll,
    Feedback,
    Game,
    GameSuggestion,
    HomunculusUpgrade,
    Season,
    Submission,
    User,
    UserAchievement,
    UserPreference,
    UserStreak,
    UsageEvent,
    get_engine,
)
from bot.db.personal_bests import PersonalBests, get_best_base_score, get_personal_bests
from bot.db.preferences import get_opted_in_preferences, get_preference, set_preference
from bot.db.seasons import get_current_season, get_season_ending_yesterday
from bot.db.streaks import (
    GameDigestData,
    MAX_FREEZES,
    WeeklyDigestData,
    get_all_streaks,
    get_streak,
    get_user_best_streaks,
    get_user_streak,
    get_user_total_freezes,
    get_weekly_digest,
    get_yesterday_digest,
    update_streak_on_submission,
)
from bot.db.submissions import (
    UserSummary,
    add_submission_manual,
    bulk_delete_submissions,
    delete_submission,
    get_users_summary,
    is_duplicate,
    recalculate_game_ranks,
    record_submission,
    upsert_user,
)
from bot.db.suggestions import (
    add_suggestion,
    create_daily_poll,
    find_similar_name,
    get_latest_unnotified_poll,
    get_unpolled_suggestions,
    mark_poll_notified,
)
from bot.db.usage import get_usage_events, get_usage_summary, log_usage_event

__all__ = [
    "AdminConfig",
    "AppLog",
    "Base",
    "DailyPoll",
    "Feedback",
    "Game",
    "GameDifficultyMetrics",
    "GameDifficultyRow",
    "GameSpeedBonusStats",
    "GameSuggestion",
    "HomunculusUpgrade",
    "KpiToday",
    "Season",
    "ScoreBucket",
    "ScoreTimePoint",
    "SpeedBonusLeader",
    "Submission",
    "User",
    "UserAchievement",
    "UserGameRow",
    "UserPreference",
    "UserScorePoint",
    "UserStreak",
    "UsageEvent",
    "get_engine",
    "UserSummary",
    "add_feedback",
    "add_submission_manual",
    "bulk_delete_submissions",
    "delete_submission",
    "get_all_feedback",
    "get_avg_score_over_time",
    "get_game_difficulty_comparison",
    "get_game_difficulty_metrics",
    "get_game_raw_data_breakdown",
    "get_game_speed_bonus_stats",
    "get_kpi_today",
    "get_score_distribution",
    "get_speed_bonus_leaders",
    "get_user_per_game_stats",
    "get_user_score_history",
    "get_user_submission_dates",
    "get_users_for_h2h",
    "get_users_summary",
    "is_duplicate",
    "recalculate_game_ranks",
    "record_submission",
    "upsert_user",
    "LeaderboardRow",
    "get_leaderboard",
    "GameDigestData",
    "MAX_FREEZES",
    "WeeklyDigestData",
    "get_all_streaks",
    "get_streak",
    "get_user_best_streaks",
    "get_user_streak",
    "get_user_total_freezes",
    "get_weekly_digest",
    "get_yesterday_digest",
    "update_streak_on_submission",
    "get_current_season",
    "get_season_ending_yesterday",
    "award_season_champion",
    "get_user_achievements",
    "PersonalBests",
    "get_best_base_score",
    "get_personal_bests",
    "HeadToHeadResult",
    "get_head_to_head",
    "add_suggestion",
    "create_daily_poll",
    "find_similar_name",
    "get_latest_unnotified_poll",
    "get_unpolled_suggestions",
    "mark_poll_notified",
    "get_opted_in_preferences",
    "get_preference",
    "set_preference",
    "get_logs",
    "get_config",
    "set_config",
    "get_usage_events",
    "get_usage_summary",
    "log_usage_event",
    "add_homunculus_upgrade",
    "get_homunculus_upgrades",
    "homunculus_upgrade_exists",
]
