from bot.db.models import (
    AdminConfig,
    AppLog,
    Base,
    DailyPoll,
    Game,
    GameSuggestion,
    Season,
    Submission,
    User,
    UserAchievement,
    UserPreference,
    UserStreak,
    get_engine,
)
from bot.db.submissions import (
    UserSummary,
    add_submission_manual,
    bulk_delete_submissions,
    delete_submission,
    get_users_summary,
    is_duplicate,
    recalculate_game_ranks,
    record_submission,
    upsert_user,
)
from bot.db.leaderboard import LeaderboardRow, get_leaderboard
from bot.db.streaks import (
    GameDigestData,
    MAX_FREEZES,
    WeeklyDigestData,
    get_all_streaks,
    get_streak,
    get_user_best_streaks,
    get_user_streak,
    get_weekly_digest,
    get_yesterday_digest,
    update_streak_on_submission,
)
from bot.db.seasons import get_current_season, get_season_ending_yesterday
from bot.db.achievements import award_season_champion, get_user_achievements
from bot.db.personal_bests import PersonalBests, get_personal_bests
from bot.db.head_to_head import HeadToHeadResult, get_head_to_head
from bot.db.suggestions import (
    add_suggestion,
    create_daily_poll,
    find_similar_name,
    get_latest_unnotified_poll,
    get_unpolled_suggestions,
    mark_poll_notified,
)
from bot.db.preferences import get_opted_in_preferences, get_preference, set_preference
from bot.db.logs import get_logs
from bot.db.config import get_config, set_config

__all__ = [
    "AdminConfig",
    "AppLog",
    "Base",
    "DailyPoll",
    "Game",
    "GameSuggestion",
    "Season",
    "Submission",
    "User",
    "UserAchievement",
    "UserPreference",
    "UserStreak",
    "get_engine",
    "UserSummary",
    "add_submission_manual",
    "bulk_delete_submissions",
    "delete_submission",
    "get_users_summary",
    "is_duplicate",
    "recalculate_game_ranks",
    "record_submission",
    "upsert_user",
    "LeaderboardRow",
    "get_leaderboard",
    "GameDigestData",
    "MAX_FREEZES",
    "WeeklyDigestData",
    "get_all_streaks",
    "get_streak",
    "get_user_best_streaks",
    "get_user_streak",
    "get_weekly_digest",
    "get_yesterday_digest",
    "update_streak_on_submission",
    "get_current_season",
    "get_season_ending_yesterday",
    "award_season_champion",
    "get_user_achievements",
    "PersonalBests",
    "get_personal_bests",
    "HeadToHeadResult",
    "get_head_to_head",
    "add_suggestion",
    "create_daily_poll",
    "find_similar_name",
    "get_latest_unnotified_poll",
    "get_unpolled_suggestions",
    "mark_poll_notified",
    "get_opted_in_preferences",
    "get_preference",
    "set_preference",
    "get_logs",
    "get_config",
    "set_config",
]
